name: rssyoutubefschmtz
description: Rss Reader for Youtube
publish_to: 'none'
version: 4.4.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http:
  path_provider:
  provider:
  shared_preferences:
  share:
  url_launcher:
  webfeed:
  jiffy:
  sqflite:
  animate_do:
  flutter_lints:
  easy_dynamic_theme:
  cupertino_icons: ^1.0.0
  dynamic_color: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/